# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_run_jpg',
            name='jpg_address',
            field=models.CharField(max_length=200, verbose_name='图片连接地址'),
        ),
        migrations.AlterField(
            model_name='index_run_jpg',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='index_run_jpg',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='index_run_jpg',
            name='to_goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='具体商品连接'),
        ),
    ]
