# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181123_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active_goods',
            options={'verbose_name': '活动专区展示商品表'},
        ),
        migrations.AlterModelOptions(
            name='goods_class',
            options={'verbose_name': '分类页面分类表'},
        ),
        migrations.AlterModelOptions(
            name='goods_jpg',
            options={'verbose_name': '商品详细页面轮播图'},
        ),
        migrations.AlterModelOptions(
            name='goods_sku',
            options={'verbose_name': '商品详细参数表'},
        ),
        migrations.AlterModelOptions(
            name='goods_sup',
            options={'verbose_name': '商品类别表'},
        ),
        migrations.AlterModelOptions(
            name='index_active_area',
            options={'verbose_name': '首页专区名称表'},
        ),
        migrations.AlterModelOptions(
            name='index_active_list',
            options={'verbose_name': '首页推荐活动表'},
        ),
        migrations.AlterModelOptions(
            name='index_run_jpg',
            options={'verbose_name': '首页商品轮播图'},
        ),
    ]
