# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181123_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_form',
            name='deletes',
            field=models.BooleanField(default=False),
        ),
    ]
