# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 10:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20181124_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_sup',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='public_form',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='public_form',
            name='deletes',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
