# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20181128_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list_number', models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='订单编号')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('get_person', models.CharField(max_length=20, verbose_name='收货人')),
                ('get_person_tel', models.IntegerField(verbose_name='收货人电话')),
                ('order_address', models.CharField(max_length=200, verbose_name='订单地址')),
                ('order_status', models.IntegerField(choices=[(0, '代付款'), (1, '退发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')])),
                ('rel_pay_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付款')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order_sku_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('link_to_order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order_list', verbose_name='连接订单表ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pay_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='支付方式名称')),
                ('pay_img', models.ImageField(upload_to='order/index/%Y%m%d', verbose_name='商标图连接')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='运输方式名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运输单价')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order_list',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Pay_style', verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Transport_style', verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户的id'),
        ),
    ]
