# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0007_auto_20181125_1041'),
        ('users', '0007_auto_20181128_1010'),
        ('order', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list_number', models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('get_person', models.CharField(max_length=20, verbose_name='收货人')),
                ('get_person_tel', models.IntegerField(verbose_name='收货人电话')),
                ('order_address', models.CharField(max_length=200, verbose_name='订单地址')),
                ('order_status', models.IntegerField(choices=[(0, '代付款'), (1, '退发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')])),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='new_order_sku_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_count', models.IntegerField(verbose_name='订单数量')),
                ('sku_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sku_单价')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_SKU', verbose_name='连接sku')),
                ('link_order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.new_Order_list', verbose_name='连接订单详情')),
            ],
        ),
        migrations.CreateModel(
            name='new_Pay_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='支付方式名称')),
                ('pay_img', models.ImageField(upload_to='order/index/%Y%m%d', verbose_name='支付图片')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='new_Transport_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='运输方式名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运输单价')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletes', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='new_order_list',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.new_Pay_style', verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='new_order_list',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.new_Transport_style', verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='new_order_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户的id'),
        ),
    ]
