# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181128_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_transport_style',
            options={'verbose_name': '运输方式表', 'verbose_name_plural': '运输方式表'},
        ),
        migrations.AddField(
            model_name='new_order_list',
            name='rel_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='真是总金额'),
        ),
    ]
