# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20181130_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order_list',
            name='order_status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '退发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0),
        ),
    ]
