# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181130_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_order_list',
            name='get_person_tel',
            field=models.CharField(max_length=11, verbose_name='收货人电话'),
        ),
    ]
