# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181120_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheng', models.CharField(max_length=50, verbose_name='sheng')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('area', models.CharField(max_length=50, verbose_name='区')),
                ('detail', models.CharField(max_length=200, verbose_name='详细地址')),
                ('person', models.CharField(max_length=20, verbose_name='收货人')),
                ('linktel', models.ImageField(upload_to='', verbose_name='联系电话')),
                ('defaults', models.BooleanField(default=False, verbose_name='是否是默认地址')),
                ('builttime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='headjpg',
            field=models.FileField(null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel',
            field=models.IntegerField(verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='linkusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='连接用户列表'),
        ),
    ]
