# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181127_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='area',
            new_name='harea',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='hproper',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='sheng',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='hcity',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='省'),
            preserve_default=False,
        ),
    ]
