# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181127_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='delets',
            field=models.BooleanField(default=False),
        ),
    ]
