# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraddress_delets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='hcity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='hproper',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市'),
        ),
    ]
